### ISSUE TITLE
Notebook output

### ISSUE THREAD

**Issue by jrob93** [lsst-uk/lsst-adler#93]
Should we remove the commit hook that clears output from jupyter notebooks?

My personal preference is to show output in any example notebooks as I have found that useful when looking up software packages!

**Comment by astronomerritt** [comment]
Just to reiterate what I've said on Slack: I agree, it's definitely useful and desirable to have this output visible!! 

However, it doesn't have to be in the repo. [Sorcha runs and displays the Jupyter notebooks in the docs](https://sorcha.readthedocs.io/en/latest/notebooks.html).

The argument for clearing the output is that it adds size to the repo. If we only have a few notebooks, this isn't so much of an issue. If we later move to having many validation notebooks with a lot of plots, we might want to move down the Sorcha route.

**Comment by jrob93** [comment]
Cool that sounds like a good solution too! I suppose we don't really need the output until we are at the stage of people looking through the docs anyway
